program   = { statement | block }
block     = "{" {statement}  "}"
statement = funcDeclStatement
          | identifierDeclStatment
          | assignStatment
          | expression ";"
funcDeclStatement = "func" identifier "("[identifier{"," identifier}] ")" block
identifierDeclStatment  = "var" identifier "="  expression ";"
assignStatment  = identifier  "=" expression  ";"
expression  = computeExpression
            | 