program   = { statement | block }
block     = "{" {statement}  "}"
statement = funcDeclStatement
          | identifierDeclStatment
          | assignStatment
          | returnStatment
          | exprStatment
exprStatment = expression ";"
funcDeclStatement = "func" identifier "("[identifier{"," identifier}] ")" block
identifierDeclStatment  = "var" identifier "="  expression ";"
                        | "var" identifier;
assignStatment  = identifier  "=" expression  ";"
expression  = term  {"+" | "-" term}
term  = factor  {"*" | "/" factor}
factor = primary  
primary =  NUMBER | functionCall | "("  expression  ")" | identifier
functionCall  = identifier  "(" [ expression {"," expression} ] ")"
